# -*- coding: utf-8 -*-
"""massai_miniproject1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MDnj66anVAJQu-9yHN-Bjg2_JNdIQjPu
"""

# Step 1: import libraries

import requests
import json
import time
from datetime import datetime
import os

print("Setup done")

# Step 2: API URLs

top_url = "https://hacker-news.firebaseio.com/v0/topstories.json"
item_url = "https://hacker-news.firebaseio.com/v0/item/{}.json"

headers = {
    "User-Agent": "TrendPulse/1.0"
}

# Step 3: categories (based on keywords)

categories = {
    "technology": ["ai", "tech", "software", "data", "cloud"],
    "worldnews": ["war", "government", "election", "global"],
    "sports": ["game", "team", "player", "league"],
    "science": ["research", "space", "physics", "biology"],
    "entertainment": ["movie", "music", "show", "film"]
}

# Step 4: function to find category

def find_category(title):

    title = title.lower()

    for cat in categories:
        for word in categories[cat]:
            if word in title:
                return cat

    return None

# Step 5: get top story IDs

response = requests.get(top_url, headers=headers)

print("Status:", response.status_code)

ids = response.json()

ids = ids[:500]   # take only 500

print("Total IDs:", len(ids))

# Step 6: store results

final_data = []

count = {
    "technology": 0,
    "worldnews": 0,
    "sports": 0,
    "science": 0,
    "entertainment": 0
}

# Step 7: loop through stories

for i in ids:

    try:
        r = requests.get(item_url.format(i), headers=headers)

        data = r.json()

        if data is None:
            continue

        if "title" not in data:
            continue

        cat = find_category(data["title"])

        # limit 25 per category
        if cat and count[cat] < 25:

            one_post = {
                "post_id": data.get("id"),
                "title": data.get("title"),
                "category": cat,
                "score": data.get("score"),
                "num_comments": data.get("descendants"),
                "author": data.get("by"),
                "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            }

            final_data.append(one_post)

            count[cat] += 1

        # stop when all full
        if all(count[c] >= 25 for c in count):
            break

    except:
        print("error")
        continue

# Step 8: wait (as given in question)

time.sleep(2)

# Step 9: save file

if not os.path.exists("data"):
    os.makedirs("data")

file_name = "data/trends_" + datetime.now().strftime("%Y%m%d") + ".json"

with open(file_name, "w") as f:
    json.dump(final_data, f, indent=4)

print("Done")
print("Saved:", file_name)
print("Total collected:", len(final_data))