# -*- coding: utf-8 -*-
"""task2_data_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z4C36s6nGPSt9XnxXgj8TDvmNtoLljfH
"""

import pandas as pd
import os

# Step 1: load json file
file_path = "trends_20260410.json"
df = pd.read_json(file_path)

print("Loaded rows:", len(df))


# Step 2: remove duplicates
df = df.drop_duplicates(subset="post_id")
print("After removing duplicates:", len(df))


# Step 3: remove missing values
df = df.dropna(subset=["post_id", "title", "score"])
print("After removing nulls:", len(df))


# Step 4: fix data types
df["score"] = df["score"].astype(int)
df["num_comments"] = df["num_comments"].astype(int)


# Step 5: remove low score (<5)
df = df[df["score"] >= 5]
print("After removing low scores:", len(df))


# Step 6: remove extra spaces in title
df["title"] = df["title"].str.strip()


# Step 7: create folder
if not os.path.exists("data"):
    os.makedirs("data")


# Step 8: save as csv
output_file = "data/trends_clean.csv"

df.to_csv(output_file, index=False)

print("Saved file:", output_file)


# Step 9: category summary
print("\nStories per category:")
print(df["category"].value_counts())