# -*- coding: utf-8 -*-
"""task4_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/125VR715cWpq6Hhh6l2DPSButTGvkTjR3
"""

import pandas as pd
import matplotlib.pyplot as plt
import os

# loading the csv
data = pd.read_csv("trends_analysed.csv")

print("data loaded")

# creating outputs folder
if not os.path.exists("outputs"):
    os.makedirs("outputs")

top = data.sort_values("score", ascending=False).head(10)

plt.figure()

plt.barh(top["title"].str[:50], top["score"])

plt.xlabel("score")
plt.ylabel("title")
plt.title("Top 10 stories by score")

plt.savefig("outputs/chart1_top_stories.png")

plt.close()

cat_count = data["category"].value_counts()

plt.figure()

cat_count.plot(kind="bar")

plt.xlabel("category")
plt.ylabel("count")
plt.title("Stories per category")

plt.savefig("outputs/chart2_categories.png")

plt.close()


plt.figure()

pop = data[data["is_popular"] == True]
not_pop = data[data["is_popular"] == False]

plt.scatter(pop["score"], pop["num_comments"], label="popular")
plt.scatter(not_pop["score"], not_pop["num_comments"], label="not popular")

plt.xlabel("score")
plt.ylabel("comments")
plt.title("Score vs comments")

plt.legend()

plt.savefig("outputs/chart3_scatter.png")

plt.close()



fig, ax = plt.subplots(1, 3, figsize=(15,5))

# chart 1 small
ax[0].barh(top["title"].str[:30], top["score"])
ax[0].set_title("Top stories")

# chart 2 small
cat_count.plot(kind="bar", ax=ax[1])
ax[1].set_title("Categories")

# chart 3 small
ax[2].scatter(pop["score"], pop["num_comments"])
ax[2].set_title("Score vs comments")

plt.suptitle("TrendPulse Dashboard")

plt.savefig("outputs/dashboard.png")

plt.close()


print("done")