# -*- coding: utf-8 -*-
"""task3_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18QFMXIFUowUdrUVsVaLiCHLs3ewI9Ku7
"""

import pandas as pd
import numpy as np
import os

# Step 1: load csv
file_path = "trends_clean.csv"

df = pd.read_csv(file_path)

print("Loaded data:", df.shape)

# Step 2: basic explore
print("\nFirst 5 rows:")
print(df.head())

print("\nAverage score:", df["score"].mean())
print("Average comments:", df["num_comments"].mean())


# Step 3: NumPy analysis

scores = df["score"].values

print("\n--- NumPy Stats ---")
print("Mean score:", np.mean(scores))
print("Median score:", np.median(scores))
print("Std deviation:", np.std(scores))
print("Max score:", np.max(scores))
print("Min score:", np.min(scores))


# category with most stories
top_category = df["category"].value_counts().idxmax()
count = df["category"].value_counts().max()

print("\nMost stories in:", top_category, f"({count} stories)")


# most commented story
max_comments = df["num_comments"].max()
top_story = df[df["num_comments"] == max_comments].iloc[0]

print("\nMost commented story:", top_story["title"], "-", max_comments, "comments")


# Step 4: add new columns

# engagement = comments / (score + 1)
df["engagement"] = df["num_comments"] / (df["score"] + 1)

# is_popular = score > avg score
avg_score = df["score"].mean()
df["is_popular"] = df["score"] > avg_score


# Step 5: save file

if not os.path.exists("data"):
    os.makedirs("data")

output_file = "data/trends_analysed.csv"

df.to_csv(output_file, index=False)

print("\nSaved to:", output_file)

from google.colab import files
files.download("data/trends_analysed.csv")